// Generated by CoffeeScript 1.8.0
(function() {
  var list, name, printNames, _i, _len;

  list = ['Jake', 'Taiga', 'Ivan', 'Tylor'];

  printNames = function(name) {
    if (name == null) {
      name = 'default';
    }
    return console.log(" " + name + " says hello!");
  };

  for (_i = 0, _len = list.length; _i < _len; _i++) {
    name = list[_i];
    if (name !== 'Taiga') {
      printNames(name);
    }
  }

}).call(this);
